name: Main Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      deployments: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn test

      - run: yarn lint

      - run: yarn version --prerelease --no-git-tag-version --preid ${{github.run_number}}
        working-directory: packages/roomkit-react

      - run: yarn pack
        working-directory: packages/roomkit-react

      - name: Get current version
        id: version
        run: echo tag=v$(cd packages/roomkit-react && node -p -e "require('./package.json').version") >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          tag_name: ${{steps.version.outputs.tag}}
          files: packages/roomkit-react/100mslive-roomkit-react-*.tgz
